language: python

python:
    - "3.6"

before_install:
    - pip install pytest pytest-cov
    - pip install coverage
    - pip install codecov
    - pip install numpy
    - pip install pandas

script:
    - pytest --cov=./
    
after_success:
    - codecov
